### ISSUE TITLE
Question: Is there a discord server?

### ISSUE THREAD

**Issue by SparkzOnG1thub** [Core5570RYT/FNF-CoreDEV-Engine#11]
Just asking because i wanna make a commiuty discord server

**Comment by SparkzOnG1thub** [comment]
also can you use psych engine events

**Comment by corecathx** [comment]
Yes! CDEV Engine has it's own public discord server:
https://discord.com/invite/w8sFmXsFpk

Also, CDEV Engine doesn't support Psych Engine's events.
