### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by My-Honest-Reaction** [Core5570RYT/FNF-CoreDEV-Engine#13]
## Please describe your issue. Provide extensive detail and images if possible.
![image_2024-08-28_225811753](https://github.com/user-attachments/assets/cabde0b4-27a7-4d73-9d93-671f54a750e3)

**Comment by corecathx** [comment]
It would be really helpful for me if you explain what did you do before encountering this error, thanks.

**Comment by My-Honest-Reaction** [comment]
> It would be really helpful for me if you explain what did you do before encountering this error, thanks.

Go to mods, make a mod then make a song then press esc

**Comment by corecathx** [comment]
Ah, i have fixed that bug in 1.7, just wait for the release and thank you for reporting this bug! :]
