### ISSUE TITLE
Enhancement: For people like me, add a way to make mods through source too since some people dont like using the mods menu

### ISSUE THREAD

**Issue by abandonedacc2123** [Core5570RYT/FNF-CoreDEV-Engine#3]
## What is your suggestion, and why should it be implemented?
For people like me, add a way to make mods through source too since some people dont like using the mods menu

**Comment by ShygeeGit** [comment]
bruh just edit the source code

**Comment by abandonedacc2123** [comment]
doesnt work

**Comment by abandonedacc2123** [comment]
or its a pain

**Comment by ShygeeGit** [comment]
L

**Comment by corecathx** [comment]
lol
