### ISSUE TITLE
Bug Report: I literally can't use the engine at all (lime.utlis.preloader error)

### ISSUE THREAD

**Issue by dylan012006** [Core5570RYT/FNF-CoreDEV-Engine#4]
## What version of the game are you using? Look in the bottom right corner of the main menu.
1.6.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I just ran the exe and the error showed up
## Please describe your issue. Provide extensive detail and images if possible.
All I did was download the engine via "Releases" and when I ran the exe file it shows this error:
![image](https://github.com/Core5570RYT/FNF-CDEV-Engine/assets/61915388/a51920a0-0aa8-459d-be2e-658b946a0d55)
I basically can't use the engine at all. Is there a fix for this?

**Comment by corecathx** [comment]
It looks like the "songs.json" manifest file is missing, have you tried to check the "manifest" folder of the engine? Make sure that the "songs.json" file is there

**Comment by dylan012006** [comment]
![image](https://github.com/Core5570RYT/FNF-CDEV-Engine/assets/61915388/a7f88c5e-2f8f-48a8-a646-52d7b9daa7d8)
I just checked and it's already there but the error still shows

**Comment by corecathx** [comment]
Does the "songs" folder exists on the assets folder?

**Comment by dylan012006** [comment]
![image](https://github.com/Core5570RYT/FNF-CDEV-Engine/assets/61915388/c534343c-8c65-4fc5-b661-2c9435ce2309)
Yep, And note that I didn't modify anything in the engine at all

**Comment by corecathx** [comment]
I tried to download from the Releases as well, but it runs normally for me, i don't know what thing that makes the error happened since i never got that error
![image](https://github.com/Core5570RYT/FNF-CDEV-Engine/assets/73734126/6881a917-8f65-482a-9655-efdfffe79714)
![image](https://github.com/Core5570RYT/FNF-CDEV-Engine/assets/73734126/b5eced61-d3ee-4f05-845e-a135f22ce642)

**Comment by dylan012006** [comment]
I moved the engine to my desktop and it worked somehow. This is pretty strange.

**Comment by corecathx** [comment]
ah alright, then I'll close this Issue. Thank you for reporting the bug!
